=== rameshsingh1234/onboard-service/src/unittest/python/resources/schema/aa-schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "https://json-schema.org/draft/2019-09/schema",
	"type": "object",
	"properties": {
		"ver": {
			"type": "string",
			"minLength": 1
		},
		"timestamp": {
			"type": "string",
			"minLength": 1
		},
		"txnid": {
			"type": "string",
			"minLength": 1
		},
		"requester": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string",
					"minLength": 1
				},
				"id": {
					"type": "string",
					"minLength": 1
				}
			},
			"required": [
				"name",
				"id"
			]
		},
		"entityinfo": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string",
					"minLength": 1
				},
				"id": {
					"type": "string",
					"minLength": 1
				},
				"code": {
					"type": "string",
					"minLength": 1
				},
				"entityhandle": {
					"type": "string",
					"minLength": 1
				},
				"baseurl": {
					"type": "string",
					"minLength": 1
				},
				"webviewurl": {
					"type": ["string","null"],
					"contains": {
						"type": "string",
						"minLength": 1
					}
				},
				"certificate": {
					"type": "object",
					"properties": {
						"alg": {
							"type": "string",
							"minLength": 1
						},
						"e": {
							"type": "string",
							"minLength": 1
						},
						"kid": {
							"type": "string",
							"minLength": 1
						},
						"kty": {
							"type": "string",
							"minLength": 1
						},
						"n": {
							"type": "string",
							"minLength": 1
						},
						"use": {
							"type": "string",
							"minLength": 1
						}
					},
					"required": [
						"alg",
						"e",
						"kid",
						"kty",
						"n",
						"use"
					]
				},
				"inboundports": {
					"type": [
						"array",
						"null"
					],
					"contains": {
						"type": "string",
						"minLength": 1
					}
				},
				"outboundports": {
					"type": [
						"array",
						"null"
					],
					"contains": {
						"type": "string",
						"minLength": 1
					}
				},
				"ips": {
					"type": [
						"array",
						"null"
					],
					"contains": {
						"type": "string",
						"minLength": 1
					}
				},
				"credentialsPk": {
					"type": [
						"object",
						"null"
					],
					"properties": {
						"alg": {
							"type": "string",
							"minLength": 1
						},
						"e": {
							"type": "string",
							"minLength": 1
						},
						"kid": {
							"type": "string",
							"minLength": 1
						},
						"kty": {
							"type": "string",
							"minLength": 1
						},
						"n": {
							"type": "string",
							"minLength": 1
						},
						"use": {
							"type": "string",
							"minLength": 1
						}
					},
					"required": [
						"alg",
						"e",
						"kid",
						"kty",
						"n",
						"use"
					]
				}
			},
			"required": [
				"name",
				"id",
				"code",
				"entityhandle",
				"baseurl",
				"certificate"
			]
		}
	},
	"required": [
		"ver",
		"timestamp",
		"txnid",
		"requester",
		"entityinfo"
	]
}

=== rameshsingh1234/onboard-service/src/unittest/python/resources/testEntities.json
{
	"ver": "1.0",
	"timestamp": "2021-07-30 14:21:19.0",
	"txnid": "29ae-11e8-a8d7-0290",
	"requester": {
		"name": "test",
		"id": "testEntity"
	},
	"entityinfo": {
		"name": "test",
		"id": "testEntity",
		"code": "FINVU",
		"oldEntityId": "testEntity",
		"entityhandle": "@finvu",
		"Identifiers": [{
			"category": "STRONG",
			"type": "MOBILE"
		}],
		"baseurl": "https://aauat.finvu.in/API/V1",
		"webviewurl": "https://webvwdev.finvu.in/onboarding",
		"fitypes": [
			"DEPOSIT",
			"RECURRING_DEPOSIT",
			"TERM-DEPOSIT"
		],
		"certificate": {
			"alg": "RS256",
			"e": "AQAB",
			"kid": "f676b688-07a2-450b-abb5-57fbb98ecabe",
			"kty": "RSA",
			"n": "pOFhy12KFAcIwG-vKqkMWCc8oxAbEmB7_sakwxBYN1NudI1mddWdzUhUU38M1B3McDs-actIRDxisNvFMLOwqzQCojQiuao8fh9z8roxEEZx_LR5zG-S6xNbcsMl76FoYpYofKWfNf5Nxnc_FRcS2Yi38XaGXez5Z3JO_NvNtzZtvVjGSRlXUjEBN8q2o4c-o_fA5RVsKX57duOXLWeO6jMzhulrnSEWSv0dTvH1OeJGjtF4csXro0NWa8C9F9MUwP7juH90gmrAKacFkLPaU_uyBZzwu3w14Sa4jru2g7oYVMs0IDZnwYXUw-SgixHAghMpQwKBNwCphHI9QAN0qw",
			"use": "sig"
		},
		"tokeninfo": {
			"url": "https://www.finvu.in/aa/tokens/",
			"maxcalls": 1,
			"desc": "String"
		},
		"signature": {
			"signValue": "u2j8DsVyT1azpJC_NG84Ty5KKthuCaPod7iI7w0LK9orSMhBEwwZDCxTWq4aYWAchc8"
		},
		"inboundports": [
			"8080"
		],
		"outboundports": [
			"9595"
		],
		"ips": [
			"103.224.243.153",
			"103.224.243.227"
		]
	}
}
